---
# VAR FILE FOR GOUP: all

vlans:
  # NOTE: apply_to_groups can also include an individual hostname as defined in inventory.yml
  - name: default # VLAN 1 must be defined or Ansible will keep trying to delete it (and never succeed)
    vlan_id: 1
    apply_to_groups: [all]
  - name: FW-Transit
    vlan_id: 99
    apply_to_groups: [core]
  - name: Servers
    vlan_id: 101
    apply_to_groups: [core, leaf]
  - name: vMotion
    vlan_id: 102
    apply_to_groups: [core, leaf]

ntp_source_interface: mgmt0
ntp_servers:
  - server: 10.0.0.1
    prefer: True
  - server: 10.0.0.2

motd_banner: |-
  ************************************
          MY MOTD BANNER
  ************************************

exec_banner: |-
  **************************************
    YOU ARE LOGGING INTO [HOSTNAME]
              BE NICE!!!
  **************************************

clock_configuration:
  timezone_id: CST
  summer_timezone_id: CDT
  offset_hours: -6
  offset_minutes: 0

enable_domain_lookup: no
device_domain_name: ajlab.local
dns_vrf: default
name_servers:
  - 10.0.0.1
  - 10.0.0.2