---
# VAR FILE FOR GOUP: all

vlans:
  # NOTE: apply_to_groups can also include an individual hostname as defined in inventory.yml
  - name: default # VLAN 1 must be defined or Ansible will keep trying to delete it (and never succeed)
    vlan_id: 1
    apply_to_groups: [all]
  - name: DMZ
    vlan_id: 88
    apply_to_groups: [core]
  - name: FW-Transit
    vlan_id: 99
    apply_to_groups: [core]
  - name: Servers
    vlan_id: 101
    apply_to_groups: [core, access]
  - name: vMotion
    vlan_id: 102
    apply_to_groups: [core, access]

ntp_source_interface: mgmt0
ntp_servers:
  - server: 10.0.0.1
    prefer: yes
  - server: 10.0.0.2

motd_banner: |-
  ************************************
          MY MOTD BANNER
  ************************************

exec_banner: |-
  **************************************
    YOU ARE LOGGING INTO [HOSTNAME]
              BE NICE!!!
  **************************************

clock_configuration:
  timezone_id: CST
  summer_timezone_id: CDT
  offset_hours: -6
  offset_minutes: 0

enable_domain_lookup: no
device_domain_name: ajlab.local
dns_vrf: default
name_servers:
  - 10.0.0.1
  - 10.0.0.2

# LOGGING LEVELS ARE AS FOLLOWS (USE EITHER THE NUMBER OR NAME EXACTLY AS SHOWN HERE):
# 0 emergency
# 1 alert
# 2 critical
# 3 error
# 4 warning
# 5 notification
# 6 informational
# 7 debugging
logging_source_interface: mgmt0
console_logging_level: informational
syslog_servers:
  - server: 10.0.0.1
    port: 5216
    vrf: default
    logging_level: error
  - server: 10.0.0.2
    port: 5216
    vrf: management
    logging_level: informational