---
all:
  vars: # GLOBAL VARIABLES
    ansible_user: "{{ lookup('ansible.builtin.env', 'NXOS_USER') }}"
    ansible_password: "{{ lookup('ansible.builtin.env', 'NXOS_PASS') }}"
    ansible_network_os: nxos
  children:
    core:
      hosts:
        CORE-1:
          ansible_host: 192.168.253.101
    leaf:
      hosts:
        LEAF-1:
          ansible_host: 192.168.253.102