---
# CONFIGURE NTP SERVERS

- name: Generate NTP Payload
  ansible.builtin.set_fact:
    nxos_ntp: "{{ lookup('template', 'ntp.j2') }}"

# - name: Print NTP Payload
#   ansible.builtin.debug:
#     msg: "{{ nxos_ntp.split('\n') }}"

# NOTE: THERE IS AN IDEMPOTENCY PROBLEM WITH THIS RESOURCE!!!!!!!
#       If a server's "prefer" attribute is set to "false" or "no" it will be removed and re-created every time the playbook is ran.
#       A GitHub issue has been submitted: https://github.com/ansible-collections/cisco.nxos/issues/693
- name: Configure NTP
  cisco.nxos.nxos_ntp_global:
    config: "{{ nxos_ntp | from_yaml }}"
    state: overridden